# Generated by Django 3.2 on 2021-07-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmeasurement',
            old_name='destination',
            new_name='defined_destination',
        ),
        migrations.RenameField(
            model_name='locationmeasurement',
            old_name='location',
            new_name='user_location',
        ),
    ]
